version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    ports:
      - "3005:3000"
    # volumes:
    #   - ./frontend:/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
    ports:
      - "3030:3030"
    # volumes:
    #   - ./backend:/backend

############################################
# scripts

#
# docker-compose build

#
# docker-compose up -d

#合在一起
# docker-compose up -d --build